# Generated by Django 4.2.3 on 2023-07-21 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Категория')),
                ('description', models.CharField(max_length=255, verbose_name='Описание категории')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Товар')),
                ('description', models.CharField(max_length=255, verbose_name='Описание товара')),
                ('country', models.CharField(max_length=50, verbose_name='Страна производитель')),
                ('image', models.ImageField(upload_to='images', verbose_name='Изображение товара')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость товара')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество товара')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
                ('category', models.ManyToManyField(to='shop.category')),
            ],
        ),
    ]
